// tokens.tailwind.ts — GENERATED by scripts/build-tokens.mjs. DO NOT EDIT BY HAND.
// Ergonomic Tailwind theme pointing at the CSS vars in src/styles/tokens.css.
// Merge into tailwind.config.ts `theme.extend`. NOTE: Figma "Text" colour group
// is exposed here as `fg` (so utilities read `text-fg-primary`, not `text-text-*`).
export const tokens = {
  "colors": {
    "fg": {
      "primary": "var(--colours-text-primary)",
      "secondary": "var(--colours-text-secondary)",
      "tertiary": "var(--colours-text-tertiary)",
      "disable": "var(--colours-text-disable)",
      "inverse-primary": "var(--colours-text-inverse-primary)",
      "inverse-secondary": "var(--colours-text-inverse-secondary)",
      "inverse-tertiary": "var(--colours-text-inverse-tertiary)",
      "link-default": "var(--colours-text-link-default)",
      "link-hover": "var(--colours-text-link-hover)",
      "success": "var(--colours-text-success)",
      "warning": "var(--colours-text-warning)",
      "error": "var(--colours-text-error)",
      "info": "var(--colours-text-info)"
    },
    "surface": {
      "1": "var(--colours-surface-level-1)",
      "2": "var(--colours-surface-level-2)",
      "3": "var(--colours-surface-level-3)",
      "4": "var(--colours-surface-level-4)",
      "5": "var(--colours-surface-level-5)",
      "6": "var(--colours-surface-level-6)",
      "7": "var(--colours-surface-level-7)"
    },
    "border": {
      "DEFAULT": "var(--colours-border-border)",
      "destructive-border": "var(--colours-border-destructive-border)",
      "border": "var(--colours-border-border)",
      "border-0": "var(--colours-border-border-0)",
      "border-1": "var(--colours-border-border-1)",
      "border-2": "var(--colours-border-border-2)",
      "border-3": "var(--colours-border-border-3)",
      "border-4": "var(--colours-border-border-4)",
      "border-5": "var(--colours-border-border-5)"
    },
    "brand": {
      "DEFAULT": "var(--colours-brand-brand-primary)",
      "primary": "var(--colours-brand-brand-primary)",
      "secondary": "var(--colours-brand-brand-secondary)",
      "tertiary": "var(--colours-brand-brand-tertiary)"
    },
    "input": "var(--colours-input-input)",
    "grey": {
      "50": "var(--colours-grey-50)",
      "100": "var(--colours-grey-100)",
      "200": "var(--colours-grey-200)",
      "300": "var(--colours-grey-300)",
      "400": "var(--colours-grey-400)",
      "500": "var(--colours-grey-500)",
      "600": "var(--colours-grey-600)",
      "700": "var(--colours-grey-700)",
      "800": "var(--colours-grey-800)",
      "900": "var(--colours-grey-900)",
      "950": "var(--colours-grey-950)",
      "white": "var(--colours-grey-white)",
      "black": "var(--colours-grey-black)"
    },
    "amber": {
      "50": "var(--colours-amber-50)",
      "100": "var(--colours-amber-100)",
      "200": "var(--colours-amber-200)",
      "300": "var(--colours-amber-300)",
      "400": "var(--colours-amber-400)",
      "500": "var(--colours-amber-500)",
      "600": "var(--colours-amber-600)",
      "700": "var(--colours-amber-700)",
      "800": "var(--colours-amber-800)",
      "900": "var(--colours-amber-900)",
      "950": "var(--colours-amber-950)"
    },
    "blue": {
      "50": "var(--colours-blue-50)",
      "100": "var(--colours-blue-100)",
      "200": "var(--colours-blue-200)",
      "300": "var(--colours-blue-300)",
      "400": "var(--colours-blue-400)",
      "500": "var(--colours-blue-500)",
      "600": "var(--colours-blue-600)",
      "700": "var(--colours-blue-700)",
      "800": "var(--colours-blue-800)",
      "900": "var(--colours-blue-900)",
      "950": "var(--colours-blue-950)"
    },
    "cyan": {
      "50": "var(--colours-cyan-50)",
      "100": "var(--colours-cyan-100)",
      "200": "var(--colours-cyan-200)",
      "300": "var(--colours-cyan-300)",
      "400": "var(--colours-cyan-400)",
      "500": "var(--colours-cyan-500)",
      "600": "var(--colours-cyan-600)",
      "700": "var(--colours-cyan-700)",
      "800": "var(--colours-cyan-800)",
      "900": "var(--colours-cyan-900)",
      "950": "var(--colours-cyan-950)"
    },
    "emerald": {
      "50": "var(--colours-emerald-50)",
      "100": "var(--colours-emerald-100)",
      "200": "var(--colours-emerald-200)",
      "300": "var(--colours-emerald-300)",
      "400": "var(--colours-emerald-400)",
      "500": "var(--colours-emerald-500)",
      "600": "var(--colours-emerald-600)",
      "700": "var(--colours-emerald-700)",
      "800": "var(--colours-emerald-800)",
      "900": "var(--colours-emerald-900)",
      "950": "var(--colours-emerald-950)"
    },
    "fuchsia": {
      "50": "var(--colours-fuchsia-50)",
      "100": "var(--colours-fuchsia-100)",
      "200": "var(--colours-fuchsia-200)",
      "300": "var(--colours-fuchsia-300)",
      "400": "var(--colours-fuchsia-400)",
      "500": "var(--colours-fuchsia-500)",
      "600": "var(--colours-fuchsia-600)",
      "700": "var(--colours-fuchsia-700)",
      "800": "var(--colours-fuchsia-800)",
      "900": "var(--colours-fuchsia-900)",
      "950": "var(--colours-fuchsia-950)"
    },
    "green": {
      "50": "var(--colours-green-50)",
      "100": "var(--colours-green-100)",
      "200": "var(--colours-green-200)",
      "300": "var(--colours-green-300)",
      "400": "var(--colours-green-400)",
      "500": "var(--colours-green-500)",
      "600": "var(--colours-green-600)",
      "700": "var(--colours-green-700)",
      "800": "var(--colours-green-800)",
      "900": "var(--colours-green-900)",
      "950": "var(--colours-green-950)"
    },
    "orange": {
      "50": "var(--colours-orange-50)",
      "100": "var(--colours-orange-100)",
      "200": "var(--colours-orange-200)",
      "300": "var(--colours-orange-300)",
      "400": "var(--colours-orange-400)",
      "500": "var(--colours-orange-500)",
      "600": "var(--colours-orange-600)",
      "700": "var(--colours-orange-700)",
      "800": "var(--colours-orange-800)",
      "900": "var(--colours-orange-900)",
      "950": "var(--colours-orange-950)"
    },
    "lime": {
      "50": "var(--colours-lime-50)",
      "100": "var(--colours-lime-100)",
      "200": "var(--colours-lime-200)",
      "300": "var(--colours-lime-300)",
      "400": "var(--colours-lime-400)",
      "500": "var(--colours-lime-500)",
      "600": "var(--colours-lime-600)",
      "700": "var(--colours-lime-700)",
      "800": "var(--colours-lime-800)",
      "900": "var(--colours-lime-900)",
      "950": "var(--colours-lime-950)"
    },
    "pink": {
      "50": "var(--colours-pink-50)",
      "100": "var(--colours-pink-100)",
      "200": "var(--colours-pink-200)",
      "300": "var(--colours-pink-300)",
      "400": "var(--colours-pink-400)",
      "500": "var(--colours-pink-500)",
      "600": "var(--colours-pink-600)",
      "700": "var(--colours-pink-700)",
      "800": "var(--colours-pink-800)",
      "900": "var(--colours-pink-900)",
      "950": "var(--colours-pink-950)"
    },
    "purple": {
      "50": "var(--colours-purple-50)",
      "100": "var(--colours-purple-100)",
      "200": "var(--colours-purple-200)",
      "300": "var(--colours-purple-300)",
      "400": "var(--colours-purple-400)",
      "500": "var(--colours-purple-500)",
      "600": "var(--colours-purple-600)",
      "700": "var(--colours-purple-700)",
      "800": "var(--colours-purple-800)",
      "900": "var(--colours-purple-900)",
      "950": "var(--colours-purple-950)"
    },
    "red": {
      "50": "var(--colours-red-50)",
      "100": "var(--colours-red-100)",
      "200": "var(--colours-red-200)",
      "300": "var(--colours-red-300)",
      "400": "var(--colours-red-400)",
      "500": "var(--colours-red-500)",
      "600": "var(--colours-red-600)",
      "700": "var(--colours-red-700)",
      "800": "var(--colours-red-800)",
      "900": "var(--colours-red-900)",
      "950": "var(--colours-red-950)"
    },
    "slate": {
      "50": "var(--colours-slate-50)",
      "100": "var(--colours-slate-100)",
      "200": "var(--colours-slate-200)",
      "300": "var(--colours-slate-300)",
      "400": "var(--colours-slate-400)",
      "500": "var(--colours-slate-500)",
      "600": "var(--colours-slate-600)",
      "700": "var(--colours-slate-700)",
      "800": "var(--colours-slate-800)",
      "900": "var(--colours-slate-900)",
      "950": "var(--colours-slate-950)"
    },
    "sky": {
      "50": "var(--colours-sky-50)",
      "100": "var(--colours-sky-100)",
      "200": "var(--colours-sky-200)",
      "300": "var(--colours-sky-300)",
      "400": "var(--colours-sky-400)",
      "500": "var(--colours-sky-500)",
      "600": "var(--colours-sky-600)",
      "700": "var(--colours-sky-700)",
      "800": "var(--colours-sky-800)",
      "900": "var(--colours-sky-900)",
      "950": "var(--colours-sky-950)"
    },
    "stone": {
      "50": "var(--colours-stone-50)",
      "100": "var(--colours-stone-100)",
      "200": "var(--colours-stone-200)",
      "300": "var(--colours-stone-300)",
      "400": "var(--colours-stone-400)",
      "500": "var(--colours-stone-500)",
      "600": "var(--colours-stone-600)",
      "700": "var(--colours-stone-700)",
      "800": "var(--colours-stone-800)",
      "900": "var(--colours-stone-900)",
      "950": "var(--colours-stone-950)"
    },
    "teal": {
      "50": "var(--colours-teal-50)",
      "100": "var(--colours-teal-100)",
      "200": "var(--colours-teal-200)",
      "300": "var(--colours-teal-300)",
      "400": "var(--colours-teal-400)",
      "500": "var(--colours-teal-500)",
      "600": "var(--colours-teal-600)",
      "700": "var(--colours-teal-700)",
      "800": "var(--colours-teal-800)",
      "900": "var(--colours-teal-900)",
      "950": "var(--colours-teal-950)"
    },
    "indigo": {
      "50": "var(--colours-indigo-50)",
      "100": "var(--colours-indigo-100)",
      "200": "var(--colours-indigo-200)",
      "300": "var(--colours-indigo-300)",
      "400": "var(--colours-indigo-400)",
      "500": "var(--colours-indigo-500)",
      "600": "var(--colours-indigo-600)",
      "700": "var(--colours-indigo-700)",
      "800": "var(--colours-indigo-800)",
      "900": "var(--colours-indigo-900)",
      "950": "var(--colours-indigo-950)"
    },
    "violet": {
      "50": "var(--colours-violet-50)",
      "100": "var(--colours-violet-100)",
      "200": "var(--colours-violet-200)",
      "300": "var(--colours-violet-300)",
      "400": "var(--colours-violet-400)",
      "500": "var(--colours-violet-500)",
      "600": "var(--colours-violet-600)",
      "700": "var(--colours-violet-700)",
      "800": "var(--colours-violet-800)",
      "900": "var(--colours-violet-900)",
      "950": "var(--colours-violet-950)"
    },
    "yellow": {
      "50": "var(--colours-yellow-50)",
      "100": "var(--colours-yellow-100)",
      "200": "var(--colours-yellow-200)",
      "300": "var(--colours-yellow-300)",
      "400": "var(--colours-yellow-400)",
      "500": "var(--colours-yellow-500)",
      "600": "var(--colours-yellow-600)",
      "700": "var(--colours-yellow-700)",
      "800": "var(--colours-yellow-800)",
      "900": "var(--colours-yellow-900)",
      "950": "var(--colours-yellow-950)"
    },
    "alpha-white": {
      "alpha-0": "var(--colours-alpha-white-alpha-0)",
      "alpha-001": "var(--colours-alpha-white-alpha-001)",
      "alpha-333": "var(--colours-alpha-white-alpha-333)",
      "alpha-5": "var(--colours-alpha-white-alpha-5)",
      "alpha-10": "var(--colours-alpha-white-alpha-10)",
      "alpha-15": "var(--colours-alpha-white-alpha-15)",
      "alpha-20": "var(--colours-alpha-white-alpha-20)",
      "alpha-30": "var(--colours-alpha-white-alpha-30)",
      "alpha-40": "var(--colours-alpha-white-alpha-40)",
      "alpha-50": "var(--colours-alpha-white-alpha-50)",
      "alpha-60": "var(--colours-alpha-white-alpha-60)",
      "alpha-70": "var(--colours-alpha-white-alpha-70)",
      "alpha-80": "var(--colours-alpha-white-alpha-80)",
      "alpha-90": "var(--colours-alpha-white-alpha-90)",
      "alpha-95": "var(--colours-alpha-white-alpha-95)",
      "alpha-100": "var(--colours-alpha-white-alpha-100)"
    },
    "alpha-black": {
      "alpha-0": "var(--colours-alpha-black-alpha-0)",
      "alpha-001": "var(--colours-alpha-black-alpha-001)",
      "alpha-333": "var(--colours-alpha-black-alpha-333)",
      "alpha-5": "var(--colours-alpha-black-alpha-5)",
      "alpha-10": "var(--colours-alpha-black-alpha-10)",
      "alpha-15": "var(--colours-alpha-black-alpha-15)",
      "alpha-20": "var(--colours-alpha-black-alpha-20)",
      "alpha-30": "var(--colours-alpha-black-alpha-30)",
      "alpha-40": "var(--colours-alpha-black-alpha-40)",
      "alpha-50": "var(--colours-alpha-black-alpha-50)",
      "alpha-60": "var(--colours-alpha-black-alpha-60)",
      "alpha-70": "var(--colours-alpha-black-alpha-70)",
      "alpha-80": "var(--colours-alpha-black-alpha-80)",
      "alpha-90": "var(--colours-alpha-black-alpha-90)",
      "alpha-95": "var(--colours-alpha-black-alpha-95)",
      "alpha-100": "var(--colours-alpha-black-alpha-100)"
    }
  },
  "borderRadius": {
    "none": "var(--radius-rounded-none)",
    "xs": "var(--radius-rounded-xs)",
    "sm": "var(--radius-rounded-sm)",
    "md": "var(--radius-rounded-md)",
    "lg": "var(--radius-rounded-lg)",
    "radius": "var(--radius-radius)",
    "xl": "var(--radius-rounded-xl)",
    "2xl": "var(--radius-rounded-2xl)",
    "3xl": "var(--radius-rounded-3xl)",
    "full": "var(--radius-rounded-full)"
  },
  "boxShadow": {
    "2xs": "var(--shadow-2xs)",
    "xs": "var(--shadow-xs)",
    "sm": "var(--shadow-sm)",
    "m": "var(--shadow-m)",
    "l": "var(--shadow-l)",
    "xl": "var(--shadow-xl)",
    "2xl": "var(--shadow-2xl)"
  },
  "fontSize": {
    "heading-1": [
      "var(--text-heading-1-font-size)",
      {
        "lineHeight": "var(--text-heading-1-line-height)",
        "letterSpacing": "var(--text-heading-1-letter-spacing)"
      }
    ],
    "heading-3": [
      "var(--text-heading-3-font-size)",
      {
        "lineHeight": "var(--text-heading-3-line-height)",
        "letterSpacing": "var(--text-heading-3-letter-spacing)"
      }
    ],
    "heading-2": [
      "var(--text-heading-2-font-size)",
      {
        "lineHeight": "var(--text-heading-2-line-height)",
        "letterSpacing": "var(--text-heading-2-letter-spacing)"
      }
    ],
    "heading-4": [
      "var(--text-heading-4-font-size)",
      {
        "lineHeight": "var(--text-heading-4-line-height)",
        "letterSpacing": "var(--text-heading-4-letter-spacing)"
      }
    ],
    "monospaced": [
      "var(--text-monospaced-font-size)",
      {
        "lineHeight": "var(--text-monospaced-line-height)",
        "letterSpacing": "var(--text-monospaced-letter-spacing)"
      }
    ],
    "caption": [
      "var(--text-caption-font-size)",
      {
        "lineHeight": "var(--text-caption-line-height)",
        "letterSpacing": "var(--text-caption-letter-spacing)"
      }
    ],
    "large": [
      "var(--text-large-font-size)",
      {
        "lineHeight": "var(--text-large-line-height)",
        "letterSpacing": "var(--text-large-letter-spacing)"
      }
    ],
    "regular": [
      "var(--text-regular-font-size)",
      {
        "lineHeight": "var(--text-regular-line-height)",
        "letterSpacing": "var(--text-regular-letter-spacing)"
      }
    ],
    "small": [
      "var(--text-small-font-size)",
      {
        "lineHeight": "var(--text-small-line-height)",
        "letterSpacing": "var(--text-small-letter-spacing)"
      }
    ],
    "mini": [
      "var(--text-mini-font-size)",
      {
        "lineHeight": "var(--text-mini-line-height)",
        "letterSpacing": "var(--text-mini-letter-spacing)"
      }
    ]
  },
  "fontFamily": {
    "heading": [
      "var(--text-font-definitions-font-family-headings)",
      "sans-serif"
    ],
    "sans": [
      "var(--text-font-definitions-font-family-sans)",
      "sans-serif"
    ]
  }
};
