// tokens.tailwind.ts — GENERATED by scripts/build-tokens.mjs. DO NOT EDIT BY HAND.
// Ergonomic Tailwind theme pointing at the CSS vars in src/styles/tokens.css.
// Merge into tailwind.config.ts `theme.extend`. NOTE: Figma "Text" colour group
// is exposed here as `fg` (so utilities read `text-fg-primary`, not `text-text-*`).
export const tokens = {
  "colors": {
    "fg": {
      "primary": "rgb(var(--colours-text-primary) / <alpha-value>)",
      "secondary": "rgb(var(--colours-text-secondary) / <alpha-value>)",
      "tertiary": "rgb(var(--colours-text-tertiary) / <alpha-value>)",
      "disable": "rgb(var(--colours-text-disable) / <alpha-value>)",
      "inverse-primary": "rgb(var(--colours-text-inverse-primary) / <alpha-value>)",
      "inverse-secondary": "rgb(var(--colours-text-inverse-secondary) / <alpha-value>)",
      "inverse-tertiary": "rgb(var(--colours-text-inverse-tertiary) / <alpha-value>)",
      "link-default": "rgb(var(--colours-text-link-default) / <alpha-value>)",
      "link-hover": "rgb(var(--colours-text-link-hover) / <alpha-value>)",
      "success": "rgb(var(--colours-text-success) / <alpha-value>)",
      "warning": "rgb(var(--colours-text-warning) / <alpha-value>)",
      "error": "rgb(var(--colours-text-error) / <alpha-value>)",
      "info": "rgb(var(--colours-text-info) / <alpha-value>)"
    },
    "surface": {
      "1": "rgb(var(--colours-surface-level-1) / <alpha-value>)",
      "2": "rgb(var(--colours-surface-level-2) / <alpha-value>)",
      "3": "rgb(var(--colours-surface-level-3) / <alpha-value>)",
      "4": "rgb(var(--colours-surface-level-4) / <alpha-value>)",
      "5": "rgb(var(--colours-surface-level-5) / <alpha-value>)",
      "6": "rgb(var(--colours-surface-level-6) / <alpha-value>)",
      "7": "rgb(var(--colours-surface-level-7) / <alpha-value>)"
    },
    "border": {
      "DEFAULT": "rgb(var(--colours-border-border) / <alpha-value>)",
      "destructive-border": "rgb(var(--colours-border-destructive-border) / <alpha-value>)",
      "border": "rgb(var(--colours-border-border) / <alpha-value>)",
      "border-0": "rgb(var(--colours-border-border-0) / <alpha-value>)",
      "border-1": "rgb(var(--colours-border-border-1) / <alpha-value>)",
      "border-2": "rgb(var(--colours-border-border-2) / <alpha-value>)",
      "border-3": "rgb(var(--colours-border-border-3) / <alpha-value>)",
      "border-4": "rgb(var(--colours-border-border-4) / <alpha-value>)",
      "border-5": "rgb(var(--colours-border-border-5) / <alpha-value>)"
    },
    "brand": {
      "DEFAULT": "rgb(var(--colours-brand-brand-primary) / <alpha-value>)",
      "primary": "rgb(var(--colours-brand-brand-primary) / <alpha-value>)",
      "secondary": "rgb(var(--colours-brand-brand-secondary) / <alpha-value>)",
      "tertiary": "rgb(var(--colours-brand-brand-tertiary) / <alpha-value>)"
    },
    "input": "rgb(var(--colours-input-input) / <alpha-value>)",
    "grey": {
      "50": "rgb(var(--colours-grey-50) / <alpha-value>)",
      "100": "rgb(var(--colours-grey-100) / <alpha-value>)",
      "200": "rgb(var(--colours-grey-200) / <alpha-value>)",
      "300": "rgb(var(--colours-grey-300) / <alpha-value>)",
      "400": "rgb(var(--colours-grey-400) / <alpha-value>)",
      "500": "rgb(var(--colours-grey-500) / <alpha-value>)",
      "600": "rgb(var(--colours-grey-600) / <alpha-value>)",
      "700": "rgb(var(--colours-grey-700) / <alpha-value>)",
      "800": "rgb(var(--colours-grey-800) / <alpha-value>)",
      "900": "rgb(var(--colours-grey-900) / <alpha-value>)",
      "950": "rgb(var(--colours-grey-950) / <alpha-value>)",
      "white": "rgb(var(--colours-grey-white) / <alpha-value>)",
      "black": "rgb(var(--colours-grey-black) / <alpha-value>)"
    },
    "amber": {
      "50": "rgb(var(--colours-amber-50) / <alpha-value>)",
      "100": "rgb(var(--colours-amber-100) / <alpha-value>)",
      "200": "rgb(var(--colours-amber-200) / <alpha-value>)",
      "300": "rgb(var(--colours-amber-300) / <alpha-value>)",
      "400": "rgb(var(--colours-amber-400) / <alpha-value>)",
      "500": "rgb(var(--colours-amber-500) / <alpha-value>)",
      "600": "rgb(var(--colours-amber-600) / <alpha-value>)",
      "700": "rgb(var(--colours-amber-700) / <alpha-value>)",
      "800": "rgb(var(--colours-amber-800) / <alpha-value>)",
      "900": "rgb(var(--colours-amber-900) / <alpha-value>)",
      "950": "rgb(var(--colours-amber-950) / <alpha-value>)"
    },
    "blue": {
      "50": "rgb(var(--colours-blue-50) / <alpha-value>)",
      "100": "rgb(var(--colours-blue-100) / <alpha-value>)",
      "200": "rgb(var(--colours-blue-200) / <alpha-value>)",
      "300": "rgb(var(--colours-blue-300) / <alpha-value>)",
      "400": "rgb(var(--colours-blue-400) / <alpha-value>)",
      "500": "rgb(var(--colours-blue-500) / <alpha-value>)",
      "600": "rgb(var(--colours-blue-600) / <alpha-value>)",
      "700": "rgb(var(--colours-blue-700) / <alpha-value>)",
      "800": "rgb(var(--colours-blue-800) / <alpha-value>)",
      "900": "rgb(var(--colours-blue-900) / <alpha-value>)",
      "950": "rgb(var(--colours-blue-950) / <alpha-value>)"
    },
    "cyan": {
      "50": "rgb(var(--colours-cyan-50) / <alpha-value>)",
      "100": "rgb(var(--colours-cyan-100) / <alpha-value>)",
      "200": "rgb(var(--colours-cyan-200) / <alpha-value>)",
      "300": "rgb(var(--colours-cyan-300) / <alpha-value>)",
      "400": "rgb(var(--colours-cyan-400) / <alpha-value>)",
      "500": "rgb(var(--colours-cyan-500) / <alpha-value>)",
      "600": "rgb(var(--colours-cyan-600) / <alpha-value>)",
      "700": "rgb(var(--colours-cyan-700) / <alpha-value>)",
      "800": "rgb(var(--colours-cyan-800) / <alpha-value>)",
      "900": "rgb(var(--colours-cyan-900) / <alpha-value>)",
      "950": "rgb(var(--colours-cyan-950) / <alpha-value>)"
    },
    "emerald": {
      "50": "rgb(var(--colours-emerald-50) / <alpha-value>)",
      "100": "rgb(var(--colours-emerald-100) / <alpha-value>)",
      "200": "rgb(var(--colours-emerald-200) / <alpha-value>)",
      "300": "rgb(var(--colours-emerald-300) / <alpha-value>)",
      "400": "rgb(var(--colours-emerald-400) / <alpha-value>)",
      "500": "rgb(var(--colours-emerald-500) / <alpha-value>)",
      "600": "rgb(var(--colours-emerald-600) / <alpha-value>)",
      "700": "rgb(var(--colours-emerald-700) / <alpha-value>)",
      "800": "rgb(var(--colours-emerald-800) / <alpha-value>)",
      "900": "rgb(var(--colours-emerald-900) / <alpha-value>)",
      "950": "rgb(var(--colours-emerald-950) / <alpha-value>)"
    },
    "fuchsia": {
      "50": "rgb(var(--colours-fuchsia-50) / <alpha-value>)",
      "100": "rgb(var(--colours-fuchsia-100) / <alpha-value>)",
      "200": "rgb(var(--colours-fuchsia-200) / <alpha-value>)",
      "300": "rgb(var(--colours-fuchsia-300) / <alpha-value>)",
      "400": "rgb(var(--colours-fuchsia-400) / <alpha-value>)",
      "500": "rgb(var(--colours-fuchsia-500) / <alpha-value>)",
      "600": "rgb(var(--colours-fuchsia-600) / <alpha-value>)",
      "700": "rgb(var(--colours-fuchsia-700) / <alpha-value>)",
      "800": "rgb(var(--colours-fuchsia-800) / <alpha-value>)",
      "900": "rgb(var(--colours-fuchsia-900) / <alpha-value>)",
      "950": "rgb(var(--colours-fuchsia-950) / <alpha-value>)"
    },
    "green": {
      "50": "rgb(var(--colours-green-50) / <alpha-value>)",
      "100": "rgb(var(--colours-green-100) / <alpha-value>)",
      "200": "rgb(var(--colours-green-200) / <alpha-value>)",
      "300": "rgb(var(--colours-green-300) / <alpha-value>)",
      "400": "rgb(var(--colours-green-400) / <alpha-value>)",
      "500": "rgb(var(--colours-green-500) / <alpha-value>)",
      "600": "rgb(var(--colours-green-600) / <alpha-value>)",
      "700": "rgb(var(--colours-green-700) / <alpha-value>)",
      "800": "rgb(var(--colours-green-800) / <alpha-value>)",
      "900": "rgb(var(--colours-green-900) / <alpha-value>)",
      "950": "rgb(var(--colours-green-950) / <alpha-value>)"
    },
    "orange": {
      "50": "rgb(var(--colours-orange-50) / <alpha-value>)",
      "100": "rgb(var(--colours-orange-100) / <alpha-value>)",
      "200": "rgb(var(--colours-orange-200) / <alpha-value>)",
      "300": "rgb(var(--colours-orange-300) / <alpha-value>)",
      "400": "rgb(var(--colours-orange-400) / <alpha-value>)",
      "500": "rgb(var(--colours-orange-500) / <alpha-value>)",
      "600": "rgb(var(--colours-orange-600) / <alpha-value>)",
      "700": "rgb(var(--colours-orange-700) / <alpha-value>)",
      "800": "rgb(var(--colours-orange-800) / <alpha-value>)",
      "900": "rgb(var(--colours-orange-900) / <alpha-value>)",
      "950": "rgb(var(--colours-orange-950) / <alpha-value>)"
    },
    "lime": {
      "50": "rgb(var(--colours-lime-50) / <alpha-value>)",
      "100": "rgb(var(--colours-lime-100) / <alpha-value>)",
      "200": "rgb(var(--colours-lime-200) / <alpha-value>)",
      "300": "rgb(var(--colours-lime-300) / <alpha-value>)",
      "400": "rgb(var(--colours-lime-400) / <alpha-value>)",
      "500": "rgb(var(--colours-lime-500) / <alpha-value>)",
      "600": "rgb(var(--colours-lime-600) / <alpha-value>)",
      "700": "rgb(var(--colours-lime-700) / <alpha-value>)",
      "800": "rgb(var(--colours-lime-800) / <alpha-value>)",
      "900": "rgb(var(--colours-lime-900) / <alpha-value>)",
      "950": "rgb(var(--colours-lime-950) / <alpha-value>)"
    },
    "pink": {
      "50": "rgb(var(--colours-pink-50) / <alpha-value>)",
      "100": "rgb(var(--colours-pink-100) / <alpha-value>)",
      "200": "rgb(var(--colours-pink-200) / <alpha-value>)",
      "300": "rgb(var(--colours-pink-300) / <alpha-value>)",
      "400": "rgb(var(--colours-pink-400) / <alpha-value>)",
      "500": "rgb(var(--colours-pink-500) / <alpha-value>)",
      "600": "rgb(var(--colours-pink-600) / <alpha-value>)",
      "700": "rgb(var(--colours-pink-700) / <alpha-value>)",
      "800": "rgb(var(--colours-pink-800) / <alpha-value>)",
      "900": "rgb(var(--colours-pink-900) / <alpha-value>)",
      "950": "rgb(var(--colours-pink-950) / <alpha-value>)"
    },
    "purple": {
      "50": "rgb(var(--colours-purple-50) / <alpha-value>)",
      "100": "rgb(var(--colours-purple-100) / <alpha-value>)",
      "200": "rgb(var(--colours-purple-200) / <alpha-value>)",
      "300": "rgb(var(--colours-purple-300) / <alpha-value>)",
      "400": "rgb(var(--colours-purple-400) / <alpha-value>)",
      "500": "rgb(var(--colours-purple-500) / <alpha-value>)",
      "600": "rgb(var(--colours-purple-600) / <alpha-value>)",
      "700": "rgb(var(--colours-purple-700) / <alpha-value>)",
      "800": "rgb(var(--colours-purple-800) / <alpha-value>)",
      "900": "rgb(var(--colours-purple-900) / <alpha-value>)",
      "950": "rgb(var(--colours-purple-950) / <alpha-value>)"
    },
    "red": {
      "50": "rgb(var(--colours-red-50) / <alpha-value>)",
      "100": "rgb(var(--colours-red-100) / <alpha-value>)",
      "200": "rgb(var(--colours-red-200) / <alpha-value>)",
      "300": "rgb(var(--colours-red-300) / <alpha-value>)",
      "400": "rgb(var(--colours-red-400) / <alpha-value>)",
      "500": "rgb(var(--colours-red-500) / <alpha-value>)",
      "600": "rgb(var(--colours-red-600) / <alpha-value>)",
      "700": "rgb(var(--colours-red-700) / <alpha-value>)",
      "800": "rgb(var(--colours-red-800) / <alpha-value>)",
      "900": "rgb(var(--colours-red-900) / <alpha-value>)",
      "950": "rgb(var(--colours-red-950) / <alpha-value>)"
    },
    "slate": {
      "50": "rgb(var(--colours-slate-50) / <alpha-value>)",
      "100": "rgb(var(--colours-slate-100) / <alpha-value>)",
      "200": "rgb(var(--colours-slate-200) / <alpha-value>)",
      "300": "rgb(var(--colours-slate-300) / <alpha-value>)",
      "400": "rgb(var(--colours-slate-400) / <alpha-value>)",
      "500": "rgb(var(--colours-slate-500) / <alpha-value>)",
      "600": "rgb(var(--colours-slate-600) / <alpha-value>)",
      "700": "rgb(var(--colours-slate-700) / <alpha-value>)",
      "800": "rgb(var(--colours-slate-800) / <alpha-value>)",
      "900": "rgb(var(--colours-slate-900) / <alpha-value>)",
      "950": "rgb(var(--colours-slate-950) / <alpha-value>)"
    },
    "sky": {
      "50": "rgb(var(--colours-sky-50) / <alpha-value>)",
      "100": "rgb(var(--colours-sky-100) / <alpha-value>)",
      "200": "rgb(var(--colours-sky-200) / <alpha-value>)",
      "300": "rgb(var(--colours-sky-300) / <alpha-value>)",
      "400": "rgb(var(--colours-sky-400) / <alpha-value>)",
      "500": "rgb(var(--colours-sky-500) / <alpha-value>)",
      "600": "rgb(var(--colours-sky-600) / <alpha-value>)",
      "700": "rgb(var(--colours-sky-700) / <alpha-value>)",
      "800": "rgb(var(--colours-sky-800) / <alpha-value>)",
      "900": "rgb(var(--colours-sky-900) / <alpha-value>)",
      "950": "rgb(var(--colours-sky-950) / <alpha-value>)"
    },
    "stone": {
      "50": "rgb(var(--colours-stone-50) / <alpha-value>)",
      "100": "rgb(var(--colours-stone-100) / <alpha-value>)",
      "200": "rgb(var(--colours-stone-200) / <alpha-value>)",
      "300": "rgb(var(--colours-stone-300) / <alpha-value>)",
      "400": "rgb(var(--colours-stone-400) / <alpha-value>)",
      "500": "rgb(var(--colours-stone-500) / <alpha-value>)",
      "600": "rgb(var(--colours-stone-600) / <alpha-value>)",
      "700": "rgb(var(--colours-stone-700) / <alpha-value>)",
      "800": "rgb(var(--colours-stone-800) / <alpha-value>)",
      "900": "rgb(var(--colours-stone-900) / <alpha-value>)",
      "950": "rgb(var(--colours-stone-950) / <alpha-value>)"
    },
    "teal": {
      "50": "rgb(var(--colours-teal-50) / <alpha-value>)",
      "100": "rgb(var(--colours-teal-100) / <alpha-value>)",
      "200": "rgb(var(--colours-teal-200) / <alpha-value>)",
      "300": "rgb(var(--colours-teal-300) / <alpha-value>)",
      "400": "rgb(var(--colours-teal-400) / <alpha-value>)",
      "500": "rgb(var(--colours-teal-500) / <alpha-value>)",
      "600": "rgb(var(--colours-teal-600) / <alpha-value>)",
      "700": "rgb(var(--colours-teal-700) / <alpha-value>)",
      "800": "rgb(var(--colours-teal-800) / <alpha-value>)",
      "900": "rgb(var(--colours-teal-900) / <alpha-value>)",
      "950": "rgb(var(--colours-teal-950) / <alpha-value>)"
    },
    "indigo": {
      "50": "rgb(var(--colours-indigo-50) / <alpha-value>)",
      "100": "rgb(var(--colours-indigo-100) / <alpha-value>)",
      "200": "rgb(var(--colours-indigo-200) / <alpha-value>)",
      "300": "rgb(var(--colours-indigo-300) / <alpha-value>)",
      "400": "rgb(var(--colours-indigo-400) / <alpha-value>)",
      "500": "rgb(var(--colours-indigo-500) / <alpha-value>)",
      "600": "rgb(var(--colours-indigo-600) / <alpha-value>)",
      "700": "rgb(var(--colours-indigo-700) / <alpha-value>)",
      "800": "rgb(var(--colours-indigo-800) / <alpha-value>)",
      "900": "rgb(var(--colours-indigo-900) / <alpha-value>)",
      "950": "rgb(var(--colours-indigo-950) / <alpha-value>)"
    },
    "violet": {
      "50": "rgb(var(--colours-violet-50) / <alpha-value>)",
      "100": "rgb(var(--colours-violet-100) / <alpha-value>)",
      "200": "rgb(var(--colours-violet-200) / <alpha-value>)",
      "300": "rgb(var(--colours-violet-300) / <alpha-value>)",
      "400": "rgb(var(--colours-violet-400) / <alpha-value>)",
      "500": "rgb(var(--colours-violet-500) / <alpha-value>)",
      "600": "rgb(var(--colours-violet-600) / <alpha-value>)",
      "700": "rgb(var(--colours-violet-700) / <alpha-value>)",
      "800": "rgb(var(--colours-violet-800) / <alpha-value>)",
      "900": "rgb(var(--colours-violet-900) / <alpha-value>)",
      "950": "rgb(var(--colours-violet-950) / <alpha-value>)"
    },
    "yellow": {
      "50": "rgb(var(--colours-yellow-50) / <alpha-value>)",
      "100": "rgb(var(--colours-yellow-100) / <alpha-value>)",
      "200": "rgb(var(--colours-yellow-200) / <alpha-value>)",
      "300": "rgb(var(--colours-yellow-300) / <alpha-value>)",
      "400": "rgb(var(--colours-yellow-400) / <alpha-value>)",
      "500": "rgb(var(--colours-yellow-500) / <alpha-value>)",
      "600": "rgb(var(--colours-yellow-600) / <alpha-value>)",
      "700": "rgb(var(--colours-yellow-700) / <alpha-value>)",
      "800": "rgb(var(--colours-yellow-800) / <alpha-value>)",
      "900": "rgb(var(--colours-yellow-900) / <alpha-value>)",
      "950": "rgb(var(--colours-yellow-950) / <alpha-value>)"
    },
    "alpha-white": {
      "alpha-0": "rgb(var(--colours-alpha-white-alpha-0) / <alpha-value>)",
      "alpha-001": "rgb(var(--colours-alpha-white-alpha-001) / <alpha-value>)",
      "alpha-333": "rgb(var(--colours-alpha-white-alpha-333) / <alpha-value>)",
      "alpha-5": "rgb(var(--colours-alpha-white-alpha-5) / <alpha-value>)",
      "alpha-10": "rgb(var(--colours-alpha-white-alpha-10) / <alpha-value>)",
      "alpha-15": "rgb(var(--colours-alpha-white-alpha-15) / <alpha-value>)",
      "alpha-20": "rgb(var(--colours-alpha-white-alpha-20) / <alpha-value>)",
      "alpha-30": "rgb(var(--colours-alpha-white-alpha-30) / <alpha-value>)",
      "alpha-40": "rgb(var(--colours-alpha-white-alpha-40) / <alpha-value>)",
      "alpha-50": "rgb(var(--colours-alpha-white-alpha-50) / <alpha-value>)",
      "alpha-60": "rgb(var(--colours-alpha-white-alpha-60) / <alpha-value>)",
      "alpha-70": "rgb(var(--colours-alpha-white-alpha-70) / <alpha-value>)",
      "alpha-80": "rgb(var(--colours-alpha-white-alpha-80) / <alpha-value>)",
      "alpha-90": "rgb(var(--colours-alpha-white-alpha-90) / <alpha-value>)",
      "alpha-95": "rgb(var(--colours-alpha-white-alpha-95) / <alpha-value>)",
      "alpha-100": "rgb(var(--colours-alpha-white-alpha-100) / <alpha-value>)"
    },
    "alpha-black": {
      "alpha-0": "rgb(var(--colours-alpha-black-alpha-0) / <alpha-value>)",
      "alpha-001": "rgb(var(--colours-alpha-black-alpha-001) / <alpha-value>)",
      "alpha-333": "rgb(var(--colours-alpha-black-alpha-333) / <alpha-value>)",
      "alpha-5": "rgb(var(--colours-alpha-black-alpha-5) / <alpha-value>)",
      "alpha-10": "rgb(var(--colours-alpha-black-alpha-10) / <alpha-value>)",
      "alpha-15": "rgb(var(--colours-alpha-black-alpha-15) / <alpha-value>)",
      "alpha-20": "rgb(var(--colours-alpha-black-alpha-20) / <alpha-value>)",
      "alpha-30": "rgb(var(--colours-alpha-black-alpha-30) / <alpha-value>)",
      "alpha-40": "rgb(var(--colours-alpha-black-alpha-40) / <alpha-value>)",
      "alpha-50": "rgb(var(--colours-alpha-black-alpha-50) / <alpha-value>)",
      "alpha-60": "rgb(var(--colours-alpha-black-alpha-60) / <alpha-value>)",
      "alpha-70": "rgb(var(--colours-alpha-black-alpha-70) / <alpha-value>)",
      "alpha-80": "rgb(var(--colours-alpha-black-alpha-80) / <alpha-value>)",
      "alpha-90": "rgb(var(--colours-alpha-black-alpha-90) / <alpha-value>)",
      "alpha-95": "rgb(var(--colours-alpha-black-alpha-95) / <alpha-value>)",
      "alpha-100": "rgb(var(--colours-alpha-black-alpha-100) / <alpha-value>)"
    }
  },
  "borderRadius": {
    "none": "var(--radius-rounded-none)",
    "xs": "var(--radius-rounded-xs)",
    "sm": "var(--radius-rounded-sm)",
    "md": "var(--radius-rounded-md)",
    "lg": "var(--radius-rounded-lg)",
    "radius": "var(--radius-radius)",
    "xl": "var(--radius-rounded-xl)",
    "2xl": "var(--radius-rounded-2xl)",
    "3xl": "var(--radius-rounded-3xl)",
    "full": "var(--radius-rounded-full)"
  },
  "boxShadow": {
    "2xs": "var(--shadow-2xs)",
    "xs": "var(--shadow-xs)",
    "sm": "var(--shadow-sm)",
    "m": "var(--shadow-m)",
    "l": "var(--shadow-l)",
    "xl": "var(--shadow-xl)",
    "2xl": "var(--shadow-2xl)"
  },
  "fontSize": {
    "heading-1": [
      "var(--text-heading-1-font-size)",
      {
        "lineHeight": "var(--text-heading-1-line-height)",
        "letterSpacing": "var(--text-heading-1-letter-spacing)"
      }
    ],
    "heading-3": [
      "var(--text-heading-3-font-size)",
      {
        "lineHeight": "var(--text-heading-3-line-height)",
        "letterSpacing": "var(--text-heading-3-letter-spacing)"
      }
    ],
    "heading-2": [
      "var(--text-heading-2-font-size)",
      {
        "lineHeight": "var(--text-heading-2-line-height)",
        "letterSpacing": "var(--text-heading-2-letter-spacing)"
      }
    ],
    "heading-4": [
      "var(--text-heading-4-font-size)",
      {
        "lineHeight": "var(--text-heading-4-line-height)",
        "letterSpacing": "var(--text-heading-4-letter-spacing)"
      }
    ],
    "monospaced": [
      "var(--text-monospaced-font-size)",
      {
        "lineHeight": "var(--text-monospaced-line-height)",
        "letterSpacing": "var(--text-monospaced-letter-spacing)"
      }
    ],
    "caption": [
      "var(--text-caption-font-size)",
      {
        "lineHeight": "var(--text-caption-line-height)",
        "letterSpacing": "var(--text-caption-letter-spacing)"
      }
    ],
    "large": [
      "var(--text-large-font-size)",
      {
        "lineHeight": "var(--text-large-line-height)",
        "letterSpacing": "var(--text-large-letter-spacing)"
      }
    ],
    "regular": [
      "var(--text-regular-font-size)",
      {
        "lineHeight": "var(--text-regular-line-height)",
        "letterSpacing": "var(--text-regular-letter-spacing)"
      }
    ],
    "small": [
      "var(--text-small-font-size)",
      {
        "lineHeight": "var(--text-small-line-height)",
        "letterSpacing": "var(--text-small-letter-spacing)"
      }
    ],
    "mini": [
      "var(--text-mini-font-size)",
      {
        "lineHeight": "var(--text-mini-line-height)",
        "letterSpacing": "var(--text-mini-letter-spacing)"
      }
    ]
  },
  "fontFamily": {
    "heading": [
      "var(--text-font-definitions-font-family-headings)",
      "sans-serif"
    ],
    "sans": [
      "var(--text-font-definitions-font-family-sans)",
      "sans-serif"
    ]
  }
};
